Document: dsdcc
Title: Debian dsdcc Manual
Author: <insert document author here>
Abstract: This manual describes what dsdcc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dsdcc/dsdcc.sgml.gz

Format: postscript
Files: /usr/share/doc/dsdcc/dsdcc.ps.gz

Format: text
Files: /usr/share/doc/dsdcc/dsdcc.text.gz

Format: HTML
Index: /usr/share/doc/dsdcc/html/index.html
Files: /usr/share/doc/dsdcc/html/*.html
